### ISSUE TITLE
[Component] Badges

### ISSUE THREAD

**Issue by felipefialho** [juntossomosmais/atomium#92]

**Comment by igorwessel** [comment]
@gabrielduete @3rdepaula

**Comment by felipefialho** [comment]
@igorwessel @gabrielduete @3rdepaula is possible change the status to progress 😄 

<img width="545" alt="image" src="https://github.com/juntossomosmais/atomium/assets/3603793/f9888bee-4c10-4344-b19d-c2d5b4ef40dc">

**Comment by gabrielduete** [comment]
@felipefialho Okay! We are creating [a task on the board](https://juntossomosmais.monday.com/boards/1521247929/pulses/4928114471?term=Badge&termColumns=XQAAAAK7AAAAAAAAAABBKchm8490pNojhKe2NR1Qb5fN5HJ0LXEm21hsHAJFb9dbhVng0J6mb2wL-V-02r-HRzffeJyyQLDcznYQ9-bjEBSrRkyfPVyizyoe1RAJfzw7yfwB_3cHPvMboCYEGOzt4GmFsqzttbzjfkYtJ_jnICLfRyOrdWWAOi4HIBx1o8BlkxMnP1r6POzg) for the next sprint. We will change the status as soon as we start! ❤️

**Comment by gabrielduete** [comment]
We started the development! :)

[Task](https://juntossomosmais.monday.com/boards/1521247929/pulses/4928114471)
